/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "profile.index": [],
    "profile.create": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "profile.store": [],
    "profile.updatePicture": [],
    "profile.picture.show": [
        {
            "name": "profile",
            "required": true,
            "binding": "user_id"
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "profile.show": [
        {
            "name": "profile",
            "required": true,
            "binding": "user_id"
        }
    ],
    "dashboard": [],
    "users.codes.index": [],
    "users.codes.store": [],
    "users.codes.update": [
        {
            "name": "userCode",
            "required": true,
            "binding": "id"
        }
    ],
    "users.codes.destroy": [
        {
            "name": "userCode",
            "required": true,
            "binding": "id"
        }
    ],
    "notifications.index": [],
    "notifications.markAsRead": [
        {
            "name": "id",
            "required": true
        }
    ],
    "historias.correcciones.store": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.correcciones.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        },
        {
            "name": "correccion",
            "required": true
        }
    ],
    "historias.correcciones.destroy": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        },
        {
            "name": "correccion",
            "required": true
        }
    ],
    "groups.index": [],
    "groups.create": [],
    "groups.store": [],
    "groups.show": [
        {
            "name": "group",
            "required": true,
            "binding": "id"
        }
    ],
    "groups.edit": [
        {
            "name": "group",
            "required": true,
            "binding": "id"
        }
    ],
    "groups.update": [
        {
            "name": "group",
            "required": true,
            "binding": "id"
        }
    ],
    "groups.destroy": [
        {
            "name": "group",
            "required": true,
            "binding": "id"
        }
    ],
    "groups.addMembers": [
        {
            "name": "group",
            "required": true,
            "binding": "id"
        }
    ],
    "groups.removeMembers": [
        {
            "name": "group",
            "required": true,
            "binding": "id"
        }
    ],
    "groups.assignments.store": [
        {
            "name": "group",
            "required": true,
            "binding": "id"
        }
    ],
    "groups.assignments.show": [
        {
            "name": "group",
            "required": true,
            "binding": "id"
        },
        {
            "name": "assignment",
            "required": true,
            "binding": "id"
        }
    ],
    "groups.assignments.homeworks.store": [
        {
            "name": "group",
            "required": true,
            "binding": "id"
        },
        {
            "name": "assignment",
            "required": true,
            "binding": "id"
        }
    ],
    "groups.assignments.homeworks.corrections": [
        {
            "name": "group",
            "required": true,
            "binding": "id"
        },
        {
            "name": "assignment",
            "required": true,
            "binding": "id"
        },
        {
            "name": "homework",
            "required": true,
            "binding": "id"
        }
    ],
    "pacientes.index": [],
    "pacientes.create": [],
    "pacientes.store": [],
    "pacientes.show": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "pacientes.edit": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "pacientes.update": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "pacientes.destroy": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.dashboard": [],
    "historias.index": [],
    "historias.create": [],
    "historias.store": [],
    "historias.edit": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.antfamiliares.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.antpersonales.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.modelos.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.plantratamiento.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.modificacionestratamiento.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.secuenciatratamiento.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.periodontal.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.periodontal.controlplaca.store": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.radiografias.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.periodontodiagramas.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.media.store": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.update-status": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.consentimiento.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.consentimiento.show": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "historias.odontologica.panoramicas": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "historias.odontologica.coronales": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "historias.odontologica.periapicales": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "historias.odontologica.periodontodiagramas": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "historias.odontologica.media": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "historias.show": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "endodoncia.historias.index": [],
    "endodoncia.historias.create": [],
    "endodoncia.historias.store": [],
    "endodoncia.historias.show": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "endodoncia.historias.edit": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "endodoncia.historias.update": [
        {
            "name": "historia",
            "required": true
        }
    ],
    "endodoncia.historias.destroy": [
        {
            "name": "historia",
            "required": true
        }
    ],
    "endodoncia.historias.anamnesis.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "endodoncia.historias.dolor.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "cirugia.historias.index": [],
    "cirugia.historias.store": [],
    "cirugia.historias.show": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "cirugia.historias.edit": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "cirugia.historias.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "cirugia.historias.destroy": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "cirugia.historias.file.show": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        },
        {
            "name": "file",
            "required": true
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
}
export {};
