/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "profile.index": [],
    "profile.show": [
        {
            "name": "profile",
            "required": true,
            "binding": "user_id"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "profile.create": [],
    "profile.store": [],
    "profile.updatePicture": [],
    "dashboard": [],
    "notifications.index": [],
    "notifications.markAsRead": [
        {
            "name": "id",
            "required": true
        }
    ],
    "historias.correcciones.store": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.correcciones.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        },
        {
            "name": "correccion",
            "required": true
        }
    ],
    "historias.correcciones.destroy": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        },
        {
            "name": "correccion",
            "required": true
        }
    ],
    "groups.index": [],
    "groups.show": [
        {
            "name": "group",
            "required": true,
            "binding": "id"
        }
    ],
    "groups.store": [],
    "groups.destroy": [
        {
            "name": "group",
            "required": true,
            "binding": "id"
        }
    ],
    "groups.addMembers": [
        {
            "name": "group",
            "required": true,
            "binding": "id"
        }
    ],
    "groups.removeMembers": [
        {
            "name": "group",
            "required": true,
            "binding": "id"
        }
    ],
    "pacientes.index": [],
    "pacientes.create": [],
    "pacientes.store": [],
    "pacientes.show": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "pacientes.edit": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "pacientes.update": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "pacientes.destroy": [
        {
            "name": "paciente",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.dashboard": [],
    "historias.index": [],
    "historias.create": [],
    "historias.store": [],
    "historias.edit": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.antfamiliares.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.antpersonales.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.modelos.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.plantratamiento.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.modificacionestratamiento.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.secuenciatratamiento.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.periodontal.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.radiografias.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.periodontodiagramas.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.media.store": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.odontologica.panoramicas": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "historias.odontologica.coronales": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "historias.odontologica.periapicales": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "historias.odontologica.periodontodiagramas": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "historias.odontologica.media": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        },
        {
            "name": "id",
            "required": true
        }
    ],
    "historias.show": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.historia.create": [],
    "historias.update": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.storeAntFamiliares": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.updateAntFamiliares": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.storeAntPersonales": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.updateAntPersonales": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.storeTrastornos": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.updateTrastornos": [
        {
            "name": "historia",
            "required": true
        }
    ],
    "historias.storeHistoriaOdontologica": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "historias.updateHistoriaOdontologica": [
        {
            "name": "historia",
            "required": true,
            "binding": "id"
        }
    ],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
}
export {};
